### ISSUE TITLE
Guidance on cap assembly

### ISSUE THREAD

**Issue by wangxuanyu0419** [spkware/chronic_holder#2]
Hi Max and Joao!
I have printed your NPX2.0 holder from a local commercial 3D printing provider and it looks all fine. The probe can be fastened well (haven't tested in vivo yet). But for the cap, I'm not sure how it works. I need more guidance.
The cap with an open top (np2_cap_open_top) allows the flex cable to come out from the top, that works for me.
But the np2_cap_no_headstage_bridge, which you used in your preprint, it seems that the ZIF area can't go through the small opening from the inside. How did you assemble them? It would be good to add a few photos for the assembly of caps.

**Comment by jcouto** [comment]
Hi Xuanyu,
thanks for reaching out! Great that it worked from a commercial vendor, which one did you use in case others near you need fixtures?

The cap just slides into the fixture, does this image works? For head restrained recordings, I would use the cap that stores the flex.
![image](https://github.com/spkware/chronic_holder/assets/1855379/c6cb59fd-5b78-44a0-8ae0-f798e832bc20)

The cap that lets the flex come out the top is to be used when the headstage is also cemented. 

![image](https://github.com/spkware/chronic_holder/assets/1855379/70f3a494-6f0b-4151-bec9-086dfedaafe5)

We'll post a video of how to use the caps when we get a chance. Do these diagrams help for now?

**Comment by wangxuanyu0419** [comment]
Dear Joao:

Yes! The diagrams are very helpful! Thank you!

Regarding the vendor, I'm based in Munich, Germany, and the vendor is [Protolabs](www.protolabs.com/). I used ABS-Like Grey (_Accura Xtreme Gray_, SLA) which has comparable mechanical features as the GreyPro resin for your desktop printer. The minimum feature size was 0.254mm.
The main chassis was printed without any problem. The caps I received a warning from the vendor of thin walls, but it turned out to be alright. 

![img_20240415_140737_720](https://github.com/spkware/chronic_holder/assets/61549460/da02e29d-ddd7-4210-8342-c3f4c88f193e)

One following question regarding the first figure. Do you mean for prolonged implantation, it is recommended to apply KwikSil from outside to cover the junction between the cap and the chassis?

**Comment by jcouto** [comment]
We had caps that stayed for months without KwikSil, so it is not essential. 

In some cases the cap fell off (if the print was not ideal or the ground wire was on the way) in that case, we just put the cap back on and kept recording without issues. To prevent that if falls you can just add a bit of KwikSil which can be easily removed before extraction and keeps the implant clean.
 
That's great to know about the _Accura Xtreme Gray_, thanks for sharing!
