### ISSUE TITLE
Alternative design file format

### ISSUE THREAD

**Issue by JonathanAMichaels** [spkware/chronic_holder#3]
Could you provide the design files in any other format, for example STEP? Autodesk Inventor requires a Windows system.

**Comment by jcouto** [comment]
Hi @JonathanAMichaels, thanks for the message. 

We just published [release v1.0](https://github.com/spkware/chronic_holder/releases/tag/v1.0.0) with STL and STEP files. Please let me know if there are other formats that you find useful!

Our plan is to maintain the repo with our most recent design files (editable in Inventor) and issue releases with STL, STEP and PREFORM files that are "ready to print". 

PREFORM files can be used to print directly on FormLabs printers, STL and STEP to print from vendors or using other printers.

**Comment by JonathanAMichaels** [comment]
Thanks @jcouto this is fantastic!
