### ISSUE TITLE
Increase the wall thickness of the printed parts

### ISSUE THREAD

**Issue by YangLin916** [spkware/chronic_holder#4]
Hi Joao and Max!

Thank you so much for providing such great resources. Recently, I sent the 3D printing files to Xometry for printing, but they responded that some parts of the model are too thin. Their minimum printable thickness is 0.4 mm (0.015"). Could I trouble you to thicken the parts of these files with wall thicknesses less than 0.4 mm to meet this requirement? I’m not very familiar with design software, I’d greatly appreciate your help if possible!

The files are: np2_0.12, np2_0.112, np2_0.135, and np2_cap_with_headstage 

Yang

**Comment by jcouto** [comment]
Hi Yang, 

Thanks for reaching out. 

It is hard for us to change the size of the walls without re-sizing other parts and they print just fine on FormLabs with GreyPro resin and oriented vertically (instructions in the readme). We provide PreForm files in the releases. 

If you don't have access to a FormLabs printer, perhaps contacting the vendors or choosing another would be faster? We actually print in house but know of other groups that got successful prints from external vendors - check the readme please.

I hope it helps and it works by just changing vendors but feel free to reach out on mail if you want to chat about this. 

Best, Joao
